//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETD_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_tbl
    {
        public int product_id { get; set; }
        public string item_code { get; set; }
        public string item_description { get; set; }
        public string category { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> buffer { get; set; }
        public Nullable<bool> status { get; set; }
        public string added_by { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
    }
}
