//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETD_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier_tbl
    {
        public int supplier_id { get; set; }
        public string supplier_name { get; set; }
        public string supplier_address { get; set; }
        public string supplier_email { get; set; }
        public string supplier_mobile { get; set; }
        public Nullable<bool> supplier_status { get; set; }
        public string added_by { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
    }
}
